name:                erswitcher
version:             0.1.0.0
github:              "darviarush/erswitcher-2"
license:             BSD3
author:              "Yaroslav O. Kosmina"
maintainer:          "darviarush@mail.ru"
copyright:           "Copyright (c) Yaroslav O. Kosmina"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Lang

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/darviarush/erswitcher-2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  erswitcher-exe:
    main:                Erswitcher.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - erswitcher

tests:
  erswitcher-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - erswitcher
